[versions]
agp = "8.3.1"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.9.0"
composeBom = "2023.08.00"
hiltVersion = "2.48"
kspVersion = "1.9.0-1.0.13"
hiltNavigationCompose = "1.0.0"
navigationCompose = "2.7.7"
detekt = "1.23.6"
appcompat = "1.7.0"
material = "1.12.0"
compose-material = "1.6.8"
firebase-bom = "33.1.2"
google-services = "4.4.2"
crashlytics-gradle = "3.0.2"
retrofit = "2.11.0"
okhttp = "4.12.0"
auth-java-jwt = "4.4.0"
gson = "2.11.0"
amap = "6.2.0"
compose-qr-code = "1.0.1"
room = "2.6.1"
commons-net = "3.8.0"
totp = "1.7.1"
preferences-datastore = "1.1.1"
floating-bubble-view = "0.6.5"
proto-datastore = "1.1.1"
lifecycleProcess = "2.8.7"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose"}
hilt-android = { group = "com.google.dagger", name = "hilt-android" , version.ref = "hiltVersion"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler" , version.ref = "hiltVersion"}
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose" , version.ref = "hiltNavigationCompose"}
detekt-gradle = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-material" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
auth-java-jwt = { group = "com.auth0", name = "java-jwt", version.ref = "auth-java-jwt" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
amap-location = { group = "com.amap.api", name = "location", version.ref = "amap" }
lightspark-compose-qr = { group = "com.lightspark", name = "compose-qr-code", version.ref = "compose-qr-code" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
commons-net = { group = "commons-net", name = "commons-net", version.ref = "commons-net" }
samstevens-totp = { group = "dev.samstevens.totp", name = "totp", version.ref = "totp" }
preferences-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "preferences-datastore" }
floating-bubble-view = { group = "io.github.torrydo", name = "floating-bubble-view", version.ref = "floating-bubble-view" }
proto-datastore = { group = "androidx.datastore", name = "datastore", version.ref = "proto-datastore" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinAndroidKsp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref ="hiltVersion" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
androidLibrary = { id = "com.android.library", version.ref = "agp" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlyticsGradle = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics-gradle" }

